#!/usr/bin/env bash

# this is in the root bashrc
export CODE_CONFIGS=$HOME/code/configs

# Shopts
# shopt -s histappend
shopt -s direxpand
shopt -s extglob
shopt -s cdspell
shopt -s nocaseglob
shopt -u expand_aliases
shopt -s globstar
shopt -s lithist cmdhist

# Environment
export PATH="/usr/local/sbin:/usr/local/bin:$PATH:$HOME/code/configs/pirate-setup/bin"
# export PATH="/usr/local/opt/scala@2.11/bin:/usr/local/octave/3.8.0/bin:$PATH"
export GOPATH="$HOME/code/go"
PATH="$PATH:$GOPATH/bin"
PATH="$PATH:$HOME/.cargo/bin"

if [[ $(uname) == "Darwin" ]]; then
    export JAVA_HOME=$(/usr/libexec/java_home)
else
    export JAVA_HOME="/usr/lib/jvm/default"
fi 
export ASYNC_PROFILER_DIR=$HOME/code/playground/async-profiler  
export FLAME_GRAPH_DIR=$HOME/code/playground/FlameGraph  


# Android
export ANDROID_HOME=/usr/local/opt/android-sdk
export ANDROID_NDK=/usr/local/opt/android-ndk

if [[ -f ./secrets ]]; then
	source ./secrets
fi
if [[ -f ~/.pirate-setup/secrets ]]; then
	source ~/.pirate-setup/secrets
fi
if [[ -f $CODE_CONFIGS/pirate-setup/secrets ]]; then
	source $CODE_CONFIGS/pirate-setup/secrets
fi
if [ -f $CODE_CONFIGS/pirate-setup/bash/facebook ]; then
	source $CODE_CONFIGS/pirate-setup/bash/facebook
fi
if [ -f $CODE_CONFIGS/pirate-setup/bash/zynga ]; then
	source $CODE_CONFIGS/pirate-setup/bash/zynga
fi

# Use Vim for editor
export HOMEBREW_EDITOR=nvim
export EDITOR=nvim

# Bindings
# bind 'set bind-tty-special-chars off'
bind '\C-Space':complete
bind '\C-i':menu-complete
bind '"\C-f": forward-word'
bind '"\C-b": backward-word'
# bind '"\u26F5": unix-word-rubout'
bind '"\C-w": backward-kill-word'
bind '"\e[B": history-search-forward'
bind '"\e[A": history-search-backward'


# External bash history.
# TODO: fix this CF
# ---------------------
# https://unix.stackexchange.com/questions/18212/bash-history-ignoredups-and-erasedups-setting-conflict-with-common-history
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_external_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
# PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
export HISTIGNORE="ls:ll:fg:eb:ev:fc:pwd:exit:history:cb:git st"
# PROMPT_COMMAND="history -a; history -n"
# PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"


# Configs
if hash hostname 2>/dev/null; then
    export HOSTNAME=$(hostname)
else 
    export HOSTNAME="dorker"
fi

# Still needed?
export NVIM_TUI_ENABLE_TRUE_COLOR=1

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
