#!/usr/local/bin/bash
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
#ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude="node_modules" --exclude="*.min.js" --exclude="vendor" --exclude="vendors" --exclude="target"

mv .git/tags.$$ .git/tags

#SOURCES="$(pwd)"
#FILETYPES=\*.cs
#rm -f .git/cscope.out
#find "$SOURCES" -name "$FILETYPES" -exec cscope -b {} +
#mv cscope.out .git/cscope.out


# find `pwd` -name "*.c" -o -name "*.h" -o -name "*.cpp" > cscope.files
# cscope -b -q -k
